new Vue({
	el:'#app',
	data:{
		itemarr:'',
		titarr:'',
		arr:[{
			title:'热销新品',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热销新品',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热销新品',
			imgsrc:'img/4.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热销新品',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热销新品',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/2.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'优选水果',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'卤味熟食',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'卤味熟食',
			imgsrc:'img/2.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'卤味熟食',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'卤味熟食',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'卤味熟食',
			imgsrc:'img/4.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'牛奶面包',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'牛奶面包',
			imgsrc:'img/2.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'牛奶面包',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'牛奶面包',
			imgsrc:'img/4.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热饮',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热饮',
			imgsrc:'img/2.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热饮',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'热饮',
			imgsrc:'img/4.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'冰激凌',
			imgsrc:'img/1.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'冰激凌',
			imgsrc:'img/2.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'冰激凌',
			imgsrc:'img/3.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},{
			title:'冰激凌',
			imgsrc:'img/4.jpg',
			msg:'新鲜柠檬500g/盒新鲜特价新鲜特价',
			price:'￥10.8'
		},]
	},
	methods:{
		tab(a){
			console.log(a)
			var itemarr=[]
			for (var i=0;i<this.arr.length;i++) {
				if(this.arr[i].title==a){
					itemarr.push(this.arr[i])
				}
			}
			this.itemarr=itemarr;
		}
	},
	methods:{
		tab(a){
			this.itemarr=[];
			console.log(a)
			var itemarr=[]
			for (var i=0;i<this.arr.length;i++) {
				if(this.arr[i].title==a){
					itemarr.push(this.arr[i])
				}
			}
			this.itemarr=itemarr;
		}
	},
	mounted(){
		var titarr=[];
		for (var i=0;i<this.arr.length;i++) {
			if(titarr.indexOf(this.arr[i].title)==-1){
				titarr.push(this.arr[i].title)
			}
		}
		this.titarr=titarr;
	},
	created(){
		this.itemarr=this.arr
	},
})